#!/bin/bash

set -e

run_user_systemctl() {
    echo "Running user systemctl command: systemctl --user -M itg@ $@"
    if ! sudo systemctl --user -M itg@ "$@"; then
        echo "ERROR: Failed to run systemctl --user -M itg@ $@"
    fi
}

run_systemctl() {
    echo "Running system systemctl command: systemctl $@"
    if ! sudo systemctl "$@"; then
        echo "ERROR: Failed to run systemctl $@"
    fi
}

# ITGMania restart flag watcher
run_user_systemctl stop itgmania-restart-watcher.path
run_user_systemctl stop itgmania-restart-watcher.service

# ITGMania stop flag watcher
run_user_systemctl stop itgmania-stop-watcher.path
run_user_systemctl stop itgmania-stop-watcher.service

# ITGMania reset flag watcher
run_user_systemctl stop itgmania-reset-watcher.path
run_user_systemctl stop itgmania-reset-watcher.service

# ITGMania service
run_user_systemctl stop itgmania.service

# OBS Streaming flag watcher
run_user_systemctl stop obs-streaming-watcher.path
run_user_systemctl stop obs-streaming-watcher.service

# OBS Streaming service
run_user_systemctl stop obs-streaming.service

# System restart flag watcher
run_systemctl stop os-restart-watcher.path
run_systemctl stop os-restart-watcher.service

# System shutdown flag watcher
run_systemctl stop os-shutdown-watcher.path
run_systemctl stop os-shutdown-watcher.service

# Update check service
run_systemctl stop update-check.service

# Update flag watcher
run_systemctl stop update-watcher.path
run_systemctl stop update-watcher.service

# IP address listener
run_systemctl stop ipaddr-listener.service

